[package]
name = "rustikus"
version = "0.1.0"
authors = ["Weefgetouw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.9"
rodio = "0.10.0"